import React from "react";
import "../globals.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="w-[1024px] mx-auto">
          {children}
        </div>
      </body>
    </html>
  )
}
